{% set name = "typeguard" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 92ee6a0aec9135181eae6067ebd617fd9de8d75d714fb548728a4933b1dea651

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - importlib_metadata >=3.6
    - typing_extensions >=4.7.0
  run_constrained:
    - pytest >=7

test:
  imports:
    - typeguard

about:
  home: https://github.com/agronholm/typeguard
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runtime type checker for Python
  description: |
    This library provides runtime type checking for functions defined with argument type annotations.
  doc_url: https://github.com/agronholm/typeguard
  dev_url: https://github.com/agronholm/typeguard

extra:
  recipe-maintainers:
    - jan-janssen
    - itamarst
    - agronholm
