{% set name = "typeguard" %}
{% set version = "4.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d22a89d00b453b47c49875f42b6601b961757541a2e1e0ef517b6e24213c21b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - setuptools >=64
    - setuptools-scm >=6.4
    - pip
  run:
    - typing_extensions >=4.10.0
    - python >=3.8
    - importlib-metadata >=3.6
    - typing-extensions >=4.10.0
  run_constrained:
    - pytest >=7

test:
  imports:
    - typeguard

about:
  home: https://github.com/agronholm/typeguard
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runtime type checker for Python
  description: |
    This library provides runtime type checking for functions defined with argument type annotations.
  doc_url: https://github.com/agronholm/typeguard
  dev_url: https://github.com/agronholm/typeguard

extra:
  recipe-maintainers:
    - jan-janssen
    - itamarst
    - agronholm
