{% set name = "typeguard" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d830132dcd544d3f8a2a842ea739eaa0d7c099fcebb9dcdf3802f4c9929d8191

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.4
    - pip
    - setuptools_scm
  run:
    - python >=3.4

test:
  imports:
    - typeguard

about:
  home: https://github.com/agronholm/typeguard
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Runtime type checker for Python
  description: |
    This library provides runtime type checking for functions defined with argument type annotations.
  doc_url: https://github.com/agronholm/typeguard
  dev_url: https://github.com/agronholm/typeguard

extra:
  recipe-maintainers:
    - itamarst
    - agronholm
